spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

  datasource:
    data-username: stove
    data-password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.83.32.193:3306/burning?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: true
server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
