spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  datasource:
    data-username: ssafy
    data-password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.83.32.193:3306/burning?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  mybatis:
    config-location: classpath:mybatis-config.xml
server:
  port: 8080


#  spring:
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.31.92:3306/ssafynote?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#      username: kim
#      password: kim
#
#  mybatis:
#    config-location: classpath:mybatis-config.xml
#
#  server:
#    servlet:
#      context-path: /ssafynote